### ISSUE TITLE
bad url

### ISSUE THREAD

**Issue by skribbb** [codewithriza/SlotBot#7]
**i get this error when trying to run help command**

`Ignoring exception in command help:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\SlotBot-main\main.py", line 83, in help
    await ctx.send(embed=embed,delete_after=30)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\abc.py", line 1065, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed.thumbnail.url: Not a well formed URL.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed.thumbnail.url: Not a well formed URL.`

**Comment by AKGamingYT0** [comment]
i am also getting same issue

**Comment by skribbb** [comment]
I have a new one if anyone needs message me


Sent from the all-new AOL app for iOS


On Thursday, August 22, 2024, 8:09 pm, AKGamingYT ***@***.***> wrote:




i am also getting same issue

**Comment by AKGamingYT0** [comment]
> I have a new one if anyone needs message me Sent from the all-new AOL app for iOS On Thursday, August 22, 2024, 8:09 pm, AKGamingYT ***@***.***> wrote: i am also getting same issue — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

Send me

**Comment by skribbb** [comment]
Add skribbb on discord idk how to do stuff on here lol


Sent from the all-new AOL app for iOS


On Saturday, August 24, 2024, 1:21 pm, AKGamingYT ***@***.***> wrote:





I have a new one if anyone needs message me Sent from the all-new AOL app for iOS On Thursday, August 22, 2024, 8:09 pm, AKGamingYT @.> wrote: i am also getting same issue — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.>


Send me
